### Register User Baru
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Fadholi Dev",
    "email": "fadholi@gmail.com",
    "password": "password123",
    "confPassword": "password123",
    "role": "admin"
}

### Update Nama User (Ganti UUID sesuai data di DB kamu)
PATCH http://localhost:5000/users/fe0791a7-f01d-4f30-b94b-4189b4219bf8
Content-Type: application/json

{
    "name": "Nama Baru Fadholi",
    "email": "admin@gmail.com",
    "role": "admin"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}

### Ambil Access Token Baru (Refresh Token)
GET http://localhost:5000/token

### Logout
DELETE http://localhost:5000/logout